### ISSUE TITLE
Documented this.context.placeholderProvider does not exist

### ISSUE THREAD

**Issue by spplante** [SharePoint/sp-dev-fx-extensions#110]
#### Category
- [ ] Question
- [x] Bug
- [ ] Enhancement

#### Expected or Desired Behavior
As documented [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions), **this.context.placeholderProvider** must be used in order to create content within a page placeholder.

#### Observed Behavior
After creating a ListCommandSet extension using the latest yeoman generator, the property **placeholderProvider** is not available within **this.context.[...]**

#### Steps to Reproduce
Create a new SPFX extension (list command set) and try looking for this.context.placeholderProvider

**Comment by VesaJuvonen** [comment]
this.context.placeholderProvider is exposed by ApplicationCustomizerContext, which is exposed from BaseApplicationCustomizer. Referenced documentation or tutorial was also around the application customizers. 

These properties are not available through ListCommandSet extension, so the lack of the property is as designed.

Notice that as this is not an issue related on the samples in this repository, would recommend adding these kinds of generic issues to http://aka.ms/spdev-issues, so that it will be triaged using our official processes for possible SPFx and SP Dev issues.

**Comment by spplante** [comment]
Thanks Vesa, I managed to figure this one out after more tests more completely forgot I had this issue opened, my bad. Thanks again!
