### ISSUE TITLE
ListView Commands dont render in Edge

### ISSUE THREAD

**Issue by mcowley5** [SharePoint/sp-dev-fx-extensions#127]
## Category

- [ ] Question
- [x] Bug
- [ ] Enhancement

## Expected or Desired Behavior

When using Microsoft Edge the ListView Command buttons should show when debugging.

## Observed Behavior

Debugging ListView Commands work as expected when switching to Google Chrome, however don't render on Microsoft Edge.

## Steps to Reproduce

`npm install @microsoft/generator-sharepoint`

`yo @Microsoft/sharepoint`

-Choose Extension
-Choose ListView Command Set
-Choose Default Command Set Name
-Choose Default Command Set Description

`npm install`

`gulp serve --nobrowser`

Open up SharePoint online website in Edge with the debugging query string. Browse to list and note the commands aren't there. Switch browser and use the same URL including the query string and note that it's working.

**Comment by VesaJuvonen** [comment]
As this seems to be a generic issue, would request to reopen it at the sp-dev-docs, so that we get it under the official engineering process. This issue list ONLY for issues in the samples. We use http://aka.ms/spdev-issues as a centralized location for generic issues, which are also copied to our VSO for tracking. Thx.
