### ISSUE TITLE
Context menu for document libraries using SPFx extensions

### ISSUE THREAD

**Issue by sprider** [SharePoint/sp-dev-fx-extensions#13]
#### Category
- [ ] Question

Can we enable new context menu for document libraries using SPFx extensions? 

Sample exelements.xml file content 

![snip20170620_9](https://user-images.githubusercontent.com/21008316/27355339-482c2a48-55d0-11e7-9d01-1e6324591ed9.png)

Also how to set the site collection scope for custom action?

**Comment by VesaJuvonen** [comment]
Hi Joseph,
You can attach commands to context menu by using `ClientSideExtension.ListViewCommandSet.ContextMenu` Location, like shown in the following documentation/tutorial - https://dev.office.com/sharepoint/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api#debugging-your-listview-command-set-using-gulp-serve-and-query-string-parameters.

We do not however currently support associating these list view command sets to a content type like you have defined in above elements.xml file. This is, however, excellent feedback and would appreciate if you could add that enhancement request to sp-dev-docs issue list, which is used to track and collection input around SPFx releases - https://github.com/SharePoint/sp-dev-docs/issues. 

thx for the input. In general, all SPFx questions would be good to add to the https://github.com/SharePoint/sp-dev-docs/issues since we have that synced with our local VSO tasks lists. If there are any issues on the exact samples or code in these other repositories, would add them here. 

Since the issue has been addressed, closing this one in here, but would appreciate entry in the sp-dev-docs around the request for having ListViewCommandSet support in content type level. We'd also appreciate the business case clarification around these requests so that we understand where and how this would be needed. Thx.

**Comment by sprider** [comment]
Sure, @VesaJuvonen.

This means ClientSideExtension.ListViewCommandSet.ContextMenu type Command Set should display in document library item context?

**Comment by sprider** [comment]
Sure, @VesaJuvonen.

Thank you for the update.

**Comment by ravinleague** [comment]
Hi,

We currently are using the ListView command on our modern sharepoint sites. When we select the list items, we are intercepting a export to excel functionality. While everything is working as expected, we were not able to export the fields just on the listview page. the event.selectedrows is giving us all columns (internal and custom). How do we configureit to just get those fields that are visible on the list view page ?
