### ISSUE TITLE
Deploy sharepoint framework extension to sharepoint site collection #spfx #spfx-extensions 

### ISSUE THREAD

**Issue by lazaki** [SharePoint/sp-dev-fx-extensions#14]
#### Category
- [ ] Bug

#### Expected or Desired Behavior
Deploy sharepoint framework extension to my sharepoint site collection

#### Observed Behavior
My package not valid when upload it on my App Catalog

#### Steps to Reproduce
I try it with both, my sharepoint framework extension and with react-slider-field-customizer([https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/react-field-slider]) in both cases i get this:
![deploy-error](https://user-images.githubusercontent.com/11733539/27373292-0b06040c-5668-11e7-948e-7efaac5b2093.png)

my app packages is not valid.

Here is my configuration files:
package-solution:
![package-solution](https://user-images.githubusercontent.com/11733539/27373357-46ed4f2a-5668-11e7-8c51-0ff5e4bf4e2e.png)

manifest:
![manifest json](https://user-images.githubusercontent.com/11733539/27373430-82980236-5668-11e7-98e7-73027df8cd0c.png)

elements.xml
![elements xml](https://user-images.githubusercontent.com/11733539/27373461-a4726eb4-5668-11e7-861e-f27e5470001a.png)

I executed comands:
- gulp bundle
- gulp package-solution

**Comment by giuleon** [comment]
Hi,

you need of a developer tenant because SharePoint Framework Extensions is in preview at the moment.
Here you can create a dev tenant:
https://dev.office.com/devprogram

regards

**Comment by lazaki** [comment]
Thank yot 👍 @giuleon ! 

Do you have information when GA will be available?

**Comment by giuleon** [comment]
I don't know exactly, sorry.

**Comment by VesaJuvonen** [comment]
We do not have yet ETA for the GA, since this is dependent on the feedback we are getting during dev preview. GA can be estimated to happen somewhere between now and Ignite conference in September. Unless I'm mistaken, you tried to use Extensions in some other tenant type, so closing this issue now. If that was a wrong conclusion, please reopen or comment.

Notice that you can see the exact reason for the package to fail by clicking **unavailable apps** link in the page. That shows you error column in the list of solutions.
