### ISSUE TITLE
 Application Customizer and search index

### ISSUE THREAD

**Issue by tavikukko** [SharePoint/sp-dev-fx-extensions#36]
#### Category
- [x ] Question
- [ ] Bug
- [ ] Enhancement

Will the Application Customizer in PageHeader placeholder get indexed as a content? Meaning if we store some custom metadata there, can we use search to look for the page?

**Comment by VesaJuvonen** [comment]
Hi Tomi,
would suggest resubmitting this to sp-dev-docs issue list, since that's the right place for miscellaneous questions. We do sync that to VSO and have dedicated people on addressing those issues. Question is good and can't answer that 100% directly - so will close this and hopefully you can resubmit to https://github.com/SharePoint/sp-dev-docs/issues. Thx.
