### ISSUE TITLE
Cannot find module '@microsoft/node-core-library'

### ISSUE THREAD

**Issue by shakykhan** [SharePoint/sp-dev-fx-extensions#44]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Bug

#### Expected or Desired Behavior
Solution should build successfully. Already setup my dev machine and tested webpart on dev machine workbench and SharePoint Online workbench as well. Still the old solution working fine.

#### Observed Behavior
_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce
With the new solution 
When i am using gulp serve or gulp serve--, its throwing the following error

at Module.load (module.js:487:32) code: 'MODULE_NOT_FOUND' }
Error - Unknown
Cannot find module '@microsoft/node-core-library'

**Comment by VesaJuvonen** [comment]
Hi @shakykhan, to be able to understand what goes wrong, we'd need to understand also what version of the SPFx you are using and what kind of solution you created. In general, we try to drive all general SPFx issues towards https://github.com/SharePoint/sp-dev-docs/issues list, which is automatically synced to our VSO task lists... this means that you will have much faster support by entering this kind of entry there with sufficient details. I'll close this one, but would suggest creating a new one in the sp-dev-docs issue list so that we can help you to get your issue resolved. Thx.
