### ISSUE TITLE
The Readme Instructions need Updating to 1.4.0

### ISSUE THREAD

**Issue by NPrice99** [SharePoint/sp-dev-fx-extensions#84]
#### Important

Use the following form to submit an issue only if it's related to samples in this repo. If you have an issue related to the SharePoint Framework or its documentation, please submit the issue at [https://github.com/SharePoint/sp-dev-docs/issues/new](https://github.com/SharePoint/sp-dev-docs/issues/new). This will help us respond to your issue faster.

----

Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. 

#### Category
- [ ] Question
- [ ] Bug
- [ X] Enhancement

#### Expected or Desired Behavior
You do not need to drag and drop the deploy folder contents anymore in 1.4.0 as everything is packaged in the .sppkg file

#### Observed Behavior
Current Instructions say drag and drop deploy contents of folder.

Thanks for your contribution! Sharing is caring.

**Comment by VesaJuvonen** [comment]
Hi @NPrice99, this really depends if the solution has been updated to the 1.4 version and how the settings have been set in the package-solution.json. You did not mention which readme you are referring here, so could not double check the situation or fix potentially things, so would request additional details.

**Comment by LouFarho** [comment]
@VesaJuvonen How does one know if it has been updated or needs to be updated to 1.4 
I am looking at this sample:
https://github.com/SharePoint/sp-dev-fx-extensions/tree/master/samples/react-application-tenant-global-navbar 

I see steps in the instructions which I don't understand since i am newer to this.
in the deployment section:
Publish the solution on any hosting environment or CDN and update the cdnBasePath property in the write-manifests.json file with the base URL of your hosting environment

What does one do if it is to be hosted in the tenant CDN?

Upload the content of the ./temp/deploy subfolder of the sample root folder into the target hosting environment.

What is this?

and then a typo here for the package name:
add to the "Apps for SharePoint" library of the AppCatalog in your tenant the spfx-discuss-now.spppkg file that you will find under the ./sharepoint/solution subfolder of the sample root folder

I am still going thru your tutorials so maybe some of this will become clear or its just needs to be updated. If there is a tutorial on that, I am willing to perform that task.

**Comment by VesaJuvonen** [comment]
@LouFarho - Hopefully things are now clearer, but if not - feel free to open up an issue. If your issue is generic and not towards any specific sample, would recommend opening it at http://aka.ms/spdev-issues.

@NPrice99 - Closing this for now due to no response to my question.
